[2024-07-29T15:19:29.407+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-29T15:19:29.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.load_csv_to_postgres manual__2024-07-29T15:19:27.465799+00:00 [queued]>
[2024-07-29T15:19:29.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.load_csv_to_postgres manual__2024-07-29T15:19:27.465799+00:00 [queued]>
[2024-07-29T15:19:29.446+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-29T15:19:29.466+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2024-07-29 15:19:27.465799+00:00
[2024-07-29T15:19:29.473+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=936) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-29T15:19:29.475+0000] {standard_task_runner.py:64} INFO - Started process 938 to run task
[2024-07-29T15:19:29.475+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'load_csv_to_postgres', 'manual__2024-07-29T15:19:27.465799+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/csv.py', '--cfg-path', '/tmp/tmpp2rst6dm']
[2024-07-29T15:19:29.477+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask load_csv_to_postgres
[2024-07-29T15:19:29.527+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.load_csv_to_postgres manual__2024-07-29T15:19:27.465799+00:00 [running]> on host 9dd1e705964b
[2024-07-29T15:19:29.616+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T15:19:27.465799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-29T15:19:27.465799+00:00'
[2024-07-29T15:19:29.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-29T15:19:29.627+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-07-29T15:19:29.631+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-29T15:19:29.633+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv.py", line 36, in load_csv_to_postgres
    for file_name in os.listdir(CSV_FOLDER):
                     ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\intern_de\\csv'
[2024-07-29T15:19:29.649+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres, task_id=load_csv_to_postgres, run_id=manual__2024-07-29T15:19:27.465799+00:00, execution_date=20240729T151927, start_date=20240729T151929, end_date=20240729T151929
[2024-07-29T15:19:29.664+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 133 for task load_csv_to_postgres ([Errno 2] No such file or directory: 'D:\\intern_de\\csv'; 938)
[2024-07-29T15:19:29.691+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-29T15:19:29.707+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-29T15:19:29.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
