[2024-07-26T05:14:11.075+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T05:14:11.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gsheet_etl.extract_data_from_gsheet scheduled__2024-07-17T00:00:00+00:00 [queued]>
[2024-07-26T05:14:11.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gsheet_etl.extract_data_from_gsheet scheduled__2024-07-17T00:00:00+00:00 [queued]>
[2024-07-26T05:14:11.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-26T05:14:11.124+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_gsheet> on 2024-07-17 00:00:00+00:00
[2024-07-26T05:14:11.136+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gsheet_etl', 'extract_data_from_gsheet', 'scheduled__2024-07-17T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/ggsheet1.py', '--cfg-path', '/tmp/tmp7sehhav8']
[2024-07-26T05:14:11.135+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T05:14:11.138+0000] {standard_task_runner.py:91} INFO - Job 110: Subtask extract_data_from_gsheet
[2024-07-26T05:14:11.139+0000] {standard_task_runner.py:64} INFO - Started process 73 to run task
[2024-07-26T05:14:11.185+0000] {task_command.py:426} INFO - Running <TaskInstance: gsheet_etl.extract_data_from_gsheet scheduled__2024-07-17T00:00:00+00:00 [running]> on host 0da7f245b32f
[2024-07-26T05:14:11.252+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gsheet_etl' AIRFLOW_CTX_TASK_ID='extract_data_from_gsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-17T00:00:00+00:00'
[2024-07-26T05:14:11.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T05:14:11.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T05:14:11.256+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ggsheet1.py", line 17, in _extract_data_from_gsheet
    creds = ServiceAccountCredentials.from_json_keyfile_name(GOOGLE_SHEETS_CREDENTIALS_FILE, scope)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/credentials.json'
[2024-07-26T05:14:11.270+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gsheet_etl, task_id=extract_data_from_gsheet, run_id=scheduled__2024-07-17T00:00:00+00:00, execution_date=20240717T000000, start_date=20240726T051411, end_date=20240726T051411
[2024-07-26T05:14:11.282+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 110 for task extract_data_from_gsheet ([Errno 2] No such file or directory: '/path/to/your/credentials.json'; 73)
[2024-07-26T05:14:11.313+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-26T05:14:11.329+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T05:14:11.334+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
