[2024-07-30T13:29:24.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T13:29:25.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.load_csv_to_postgres scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-07-30T13:29:25.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.load_csv_to_postgres scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-07-30T13:29:25.015+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-30T13:29:25.034+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2024-07-29 00:00:00+00:00
[2024-07-30T13:29:25.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1528) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-30T13:29:25.046+0000] {standard_task_runner.py:64} INFO - Started process 1530 to run task
[2024-07-30T13:29:25.045+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'load_csv_to_postgres', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/csv.py', '--cfg-path', '/tmp/tmpxtosx3ol']
[2024-07-30T13:29:25.047+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask load_csv_to_postgres
[2024-07-30T13:29:25.101+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.load_csv_to_postgres scheduled__2024-07-29T00:00:00+00:00 [running]> on host 9dd1e705964b
[2024-07-30T13:29:25.213+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T00:00:00+00:00'
[2024-07-30T13:29:25.220+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T13:29:25.239+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-07-30T13:29:25.245+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T13:29:25.247+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv.py", line 36, in load_csv_to_postgres
    for file_name in os.listdir(CSV_FOLDER):
                     ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\intern_de\\csv'
[2024-07-30T13:29:25.269+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres, task_id=load_csv_to_postgres, run_id=scheduled__2024-07-29T00:00:00+00:00, execution_date=20240729T000000, start_date=20240730T132925, end_date=20240730T132925
[2024-07-30T13:29:25.284+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task load_csv_to_postgres ([Errno 2] No such file or directory: 'D:\\intern_de\\csv'; 1530)
[2024-07-30T13:29:25.301+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-30T13:29:25.325+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T13:29:25.330+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
